version: '3'
services:

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq_luvits
        volumes: 
            - rabbitmqdata2:/var/lib/rabbitmq
        ports:
            - "15672:15672"
            - "5672:5672"
        environment: 
            - RABBITMQ_DEFAULT_USER=guest
            - RABBITMQ_DEFAULT_PASS=guest
    
    contentmanagementapi:
        image: sander9512/contentmanagementapi
        build: contentmanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8080:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

    multimediamanagementapi:
        image: sander9512/multimediamanagementapi
        build: multimediamanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8081:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            
    customermanagementapi:
        image: sander9512/customermanagementapi
        build: customermanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8083:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

    contactmanagementapi:
        image: sander9512/contactmanagementapi
        build: contactmanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8084:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

    documentmanagementapi:
        image: sander9512/documentmanagementapi
        build: documentmanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8085:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production
            
    customerrelationmanagementapi:
        image: sander9512/customerrelationmanagementapi
        build: customerrelationmanagementapi
        depends_on:
            - rabbitmq
        ports:
            - "8082:80"
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

    contentmanagementeventhandler:
        image: sander9512/contentmanagementeventhandler
        build: contentmanagementeventhandler
        depends_on:
            - rabbitmq
        environment: 
            - ASPNETCORE_ENVIRONMENT=Production

volumes:
    rabbitmqdata2:
        external: true